name: mi_card
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/reggie.png

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
        - asset: fonts/RobotoCondensed-Italic.ttf
        - asset: fonts/RobotoCondensed-Bold.ttf
        - asset: fonts/RobotoCondensed-BoldItalic.ttf

    - family: OpenSansCondensed
      fonts:
        - asset: fonts/OpenSansCondensed-Light.ttf
        - asset: fonts/OpenSansCondensed-Bold.ttf
        - asset: fonts/OpenSansCondensed-LightItalic.ttf